// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiniegol.Core.Data;

#nullable disable

namespace Quiniegol.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824062010_PermitirResultadoNulo")]
    partial class PermitirResultadoNulo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Quiniegol.Core.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Quiniegol.Core.Models.Partido", b =>
                {
                    b.Property<int>("IdPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEquipoLocal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEquipoVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPartido");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Quiniegol.Core.Models.Pronostico", b =>
                {
                    b.Property<int>("IdPronostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdEmpleado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPartido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultadoPronosticado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPronostico");

                    b.ToTable("Pronosticos");
                });

            modelBuilder.Entity("Quiniegol.Core.Models.Usuario", b =>
                {
                    b.Property<string>("IdEmpleado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEmpleado");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
